# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('imagen', models.ImageField(upload_to='static/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='perfume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.FloatField()),
                ('presentacion', models.CharField(max_length=120)),
                ('genero', models.CharField(choices=[('M', 'Ellos'), ('F', 'Ellas')], max_length=1)),
                ('imagen', models.ImageField(upload_to='static/uploads/')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinkapp.marca')),
            ],
        ),
    ]
