# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='perfume',
            options={'verbose_name': 'Perfume', 'verbose_name_plural': 'Perfumes'},
        ),
    ]
