# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinkapp', '0002_auto_20160508_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='nombre',
            new_name='name',
        ),
    ]
