# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinkapp', '0003_auto_20160508_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='name',
            new_name='nombre',
        ),
    ]
