# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkapp', '0004_auto_20160508_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='genero',
        ),
        migrations.AddField(
            model_name='marca',
            name='generoPrincipal',
            field=models.CharField(choices=[('M', 'Ellos'), ('F', 'Ellas'), ('N', 'Ninguno')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='generoSecundario',
            field=models.CharField(choices=[('M', 'Ellos'), ('F', 'Ellas'), ('N', 'Ninguno')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfume',
            name='generoPrincipal',
            field=models.CharField(choices=[('M', 'Ellos'), ('F', 'Ellas'), ('N', 'Ninguno')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfume',
            name='generoSecundario',
            field=models.CharField(choices=[('M', 'Ellos'), ('F', 'Ellas'), ('N', 'Ninguno')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
